name: telework_env
channels:
  - defaults
  - conda-forge
  - pytorch
dependencies:
  - python=3.9
  - pandas=1.5.3
  - numpy=1.24.3
  - matplotlib=3.7.2
  - seaborn=0.12.2
  - scikit-learn=1.2.2
  - xgboost=1.7.4
  - pytorch=2.0.1
  - torchvision=0.15.2
  - joblib=1.3.2
  - pip
  - pip:
      - anyio==3.6.2
